const itemTypes = {
    FETCH_ITEMS_REQUEST:"FETCH_ITEMS_REQUEST",
    SET_ITEMS:"SET_ITEMS",
    FETCH_ITEMS_FAIL:"FETCH_ITEMS_FAIL",
    
    FETCH_ITEM_REQUEST:"FETCH_ITEM_REQUEST",
    SET_ITEM:"SET_ITEM",
    FETCH_ITEM_FAIL:"FETCH_ITEM_FAIL",
}

export default itemTypes