const saleTypes ={
    ADD_TO_SALES:"ADD_TO_SALES",
    REMOVE_SALES_ITEM:"REMOVE_SALES_ITEM",
    REDUCE_SALES_ITEM:"REDUCE_SALES_ITEM",
    SALES_EMPTY:"SALES_EMPTY",
    ADD_CALCULATED_SALE_ITEM:"ADD_CALCULATED_SALE_ITEM",
    SAVE_SALES_PAYMENT_METHOD:"SAVE_SALES_PAYMENT_METHOD",
    
}

export default saleTypes;